# Generated by Django 6.0.2 on 2026-02-18 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy_auth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='first_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='last_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(db_index=True, max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('manager', 'Manager'), ('pharmacist', 'Pharmacist'), ('cashier', 'Cashier')], default='pharmacist', max_length=50),
        ),
    ]
