# Generated by Django 6.0.2 on 2026-02-20 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy_auth', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name_plural': 'Users'},
        ),
        migrations.AlterModelTable(
            name='user',
            table='User',
        ),
    ]
