# Seeder for Table Registry - populates initial table metadata

from django.core.management.base import BaseCommand
from tables.model_definitions.table_registry import TableRegistry


def get_medicine_columns():
    """Column definitions for Medicine table."""
    return [
        {
            "name": "name",
            "label": "Medicine Name",
            "type": "string",
            "required": True,
            "description": "Name of the medicine or item",
            "example": "Paracetamol 500mg Tablets",
            "include_in_import": True,
            "include_in_export": True,
            "is_identifier": False,
            "max_length": 200,
        },
        {
            "name": "generic_name",
            "label": "Generic Name",
            "type": "string",
            "required": False,
            "description": "Generic name of the medicine",
            "example": "Paracetamol",
            "include_in_import": True,
            "include_in_export": True,
            "is_identifier": False,
            "max_length": 200,
        },
        {
            "name": "category",
            "label": "Category",
            "type": "string",
            "required": True,
            "description": "Category code or naming series",
            "example": "CAT-001",
            "include_in_import": True,
            "include_in_export": True,
            "is_identifier": False,
            "max_length": 100,
        },
        {
            "name": "cost_price",
            "label": "Cost Price",
            "type": "decimal",
            "required": True,
            "description": "Purchase cost per unit",
            "example": "25.50",
            "include_in_import": True,
            "include_in_export": True,
            "is_identifier": False,
        },
        {
            "name": "selling_price",
            "label": "Selling Price",
            "type": "decimal",
            "required": True,
            "description": "Selling price per unit",
            "example": "35.00",
            "include_in_import": True,
            "include_in_export": True,
            "is_identifier": False,
        },
        {
            "name": "barcode",
            "label": "Barcode",
            "type": "string",
            "required": True,
            "description": "Unique barcode for the item",
            "example": "8901234567890",
            "include_in_import": True,
            "include_in_export": True,
            "is_identifier": True,
            "max_length": 100,
        },
        {
            "name": "description",
            "label": "Description",
            "type": "text",
            "required": False,
            "description": "Detailed description",
            "example": "Pain relief tablets, pack of 10",
            "include_in_import": True,
            "include_in_export": True,
            "is_identifier": False,
        },
        {
            "name": "costing_method",
            "label": "Costing Method",
            "type": "choice",
            "required": False,
            "description": "Method for calculating COGS",
            "example": "fifo",
            "include_in_import": True,
            "include_in_export": True,
            "is_identifier": False,
            "choices": ["fifo", "lifo", "fefo", "average"],
        },
        # These fields are NOT included in import (system-managed)
        {
            "name": "naming_series",
            "label": "Naming Series",
            "type": "string",
            "required": False,
            "description": "Auto-generated naming series",
            "include_in_import": False,
            "include_in_export": True,
            "is_identifier": True,
        },
        {
            "name": "print",
            "label": "Print Format",
            "type": "reference",
            "required": False,
            "description": "Associated print format",
            "include_in_import": False,
            "include_in_export": False,
            "is_identifier": False,
        },
    ]


def get_category_columns():
    """Column definitions for Category table."""
    return [
        {
            "name": "name",
            "label": "Category Name",
            "type": "string",
            "required": True,
            "description": "Name of the category",
            "example": "Pain Relief Medicines",
            "include_in_import": True,
            "include_in_export": True,
            "is_identifier": False,
            "max_length": 150,
        },
        {
            "name": "description",
            "label": "Description",
            "type": "text",
            "required": False,
            "description": "Category description",
            "example": "All pain relief related medicines",
            "include_in_import": True,
            "include_in_export": True,
            "is_identifier": False,
        },
        {
            "name": "parent_category",
            "label": "Parent Category",
            "type": "string",
            "required": False,
            "description": "Parent category naming series (for subcategories)",
            "example": "CAT-001",
            "include_in_import": True,
            "include_in_export": True,
            "is_identifier": False,
        },
        # System-managed fields
        {
            "name": "naming_series",
            "label": "Naming Series",
            "type": "string",
            "required": False,
            "description": "Auto-generated naming series",
            "include_in_import": False,
            "include_in_export": True,
            "is_identifier": True,
        },
    ]


def get_supplier_columns():
    """Column definitions for Supplier table."""
    return [
        {
            "name": "name",
            "label": "Supplier Name",
            "type": "string",
            "required": True,
            "description": "Name of the supplier/vendor",
            "example": "ABC Pharmaceuticals Ltd",
            "include_in_import": True,
            "include_in_export": True,
            "is_identifier": False,
            "max_length": 200,
        },
        {
            "name": "contact_person",
            "label": "Contact Person",
            "type": "string",
            "required": False,
            "description": "Primary contact person name",
            "example": "John Smith",
            "include_in_import": True,
            "include_in_export": True,
            "is_identifier": False,
        },
        {
            "name": "phone",
            "label": "Phone",
            "type": "string",
            "required": False,
            "description": "Contact phone number",
            "example": "+251-911-123456",
            "include_in_import": True,
            "include_in_export": True,
            "is_identifier": False,
            "max_length": 20,
        },
        {
            "name": "email",
            "label": "Email",
            "type": "email",
            "required": False,
            "description": "Contact email address",
            "example": "contact@abcpharma.com",
            "include_in_import": True,
            "include_in_export": True,
            "is_identifier": False,
        },
        {
            "name": "address",
            "label": "Address",
            "type": "text",
            "required": False,
            "description": "Supplier address",
            "example": "123 Business Park, Addis Ababa",
            "include_in_import": True,
            "include_in_export": True,
            "is_identifier": False,
        },
        {
            "name": "tax_id",
            "label": "Tax ID",
            "type": "string",
            "required": False,
            "description": "Tax identification number",
            "example": "TIN-123456789",
            "include_in_import": True,
            "include_in_export": True,
            "is_identifier": True,
        },
        {
            "name": "status",
            "label": "Status",
            "type": "choice",
            "required": False,
            "description": "Supplier status",
            "example": "Active",
            "include_in_import": True,
            "include_in_export": True,
            "is_identifier": False,
            "choices": ["Active", "Inactive", "Suspended"],
        },
        # System-managed fields
        {
            "name": "naming_series",
            "label": "Naming Series",
            "type": "string",
            "required": False,
            "description": "Auto-generated naming series",
            "include_in_import": False,
            "include_in_export": True,
            "is_identifier": True,
        },
    ]


class Command(BaseCommand):
    help = "Seeds the Table Registry with initial table metadata"

    def handle(self, *args, **kwargs):
        # Define initial table data based on searchable documents
        tables_data = [
            # System module
            {
                "table_code": "system",
                "table_name": "System Hub",
                "module": "system",
                "submodule": "administration",
                "frontend_path": "/system",
                "backend_endpoint": "/api/system/",
                "search_keywords": ["system", "system hub", "system management", "administration", "admin", "settings"],
                "importable": False,
                "exportable": False,
                "description": "System administration and management hub",
                "icon": "Settings",
                "display_order": 1,
            },
            {
                "table_code": "dashboard",
                "table_name": "Dashboard",
                "module": "system",
                "submodule": "overview",
                "frontend_path": "/dashboard",
                "backend_endpoint": "/api/dashboard/",
                "search_keywords": ["dashboard", "home", "overview", "summary"],
                "importable": False,
                "exportable": True,
                "description": "Main dashboard with system overview",
                "icon": "LayoutDashboard",
                "display_order": 2,
            },
            {
                "table_code": "audit_logs",
                "table_name": "Audit Logs",
                "module": "system",
                "submodule": "security",
                "frontend_path": "/audit-logs",
                "backend_endpoint": "/api/audit-logs/",
                "search_keywords": ["audit", "audit logs", "logs", "activity"],
                "importable": False,
                "exportable": True,
                "description": "System audit logs and activity tracking",
                "icon": "ClipboardList",
                "display_order": 3,
            },
            {
                "table_code": "users",
                "table_name": "User Registry",
                "module": "system",
                "submodule": "security",
                "frontend_path": "/users",
                "backend_endpoint": "/api/users/",
                "search_keywords": ["users", "user", "accounts", "staff users"],
                "importable": True,
                "exportable": True,
                "description": "System user accounts and management",
                "icon": "Users",
                "display_order": 4,
            },

            # Inventory module - Hub
            {
                "table_code": "inventory_hub",
                "table_name": "Inventory Hub",
                "module": "inventory",
                "submodule": "hub",
                "frontend_path": "/inventory",
                "backend_endpoint": "/api/inventory-hub/",
                "search_keywords": ["inventory", "hub", "stock"],
                "importable": False,
                "exportable": False,
                "description": "Central inventory management hub",
                "icon": "Package",
                "display_order": 10,
            },

            # Inventory module - Master Data
            {
                "table_code": "medicine",
                "table_name": "Medicine Register",
                "module": "inventory",
                "submodule": "master_data",
                "frontend_path": "/inventory/medicines",
                "backend_endpoint": "/api/medicines/",
                "search_keywords": ["medicine", "medicines", "drug", "drugs", "item", "items", "item master", "medicine register", "medicine registrar"],
                "importable": True,
                "exportable": True,
                "description": "Medicine and item master data",
                "icon": "Pill",
                "db_table_name": "Medicine",
                "model_class": "tables.Medicine",
                "display_order": 20,
                "columns": get_medicine_columns(),
            },
            {
                "table_code": "category",
                "table_name": "Categories",
                "module": "inventory",
                "submodule": "master_data",
                "frontend_path": "/inventory/categories",
                "backend_endpoint": "/api/categories/",
                "search_keywords": ["category", "categories", "group", "classification"],
                "importable": True,
                "exportable": True,
                "description": "Item categories and classifications",
                "icon": "Tags",
                "db_table_name": "Category",
                "model_class": "tables.Category",
                "display_order": 21,
                "columns": get_category_columns(),
            },
            {
                "table_code": "supplier",
                "table_name": "Suppliers",
                "module": "inventory",
                "submodule": "master_data",
                "frontend_path": "/inventory/suppliers",
                "backend_endpoint": "/api/suppliers/",
                "search_keywords": ["supplier", "suppliers", "vendor", "vendors"],
                "importable": True,
                "exportable": True,
                "description": "Supplier and vendor master data",
                "icon": "Truck",
                "db_table_name": "Supplier",
                "model_class": "tables.Supplier",
                "display_order": 22,
                "columns": get_supplier_columns(),
            },

            # Inventory module - Stock Management
            {
                "table_code": "inventory_control",
                "table_name": "Inventory Control",
                "module": "inventory",
                "submodule": "stock",
                "frontend_path": "/inventory/control",
                "backend_endpoint": "/api/inventory/control/",
                "search_keywords": ["inventory", "control", "batches", "batch", "stock"],
                "importable": False,
                "exportable": True,
                "description": "Inventory control and batch management",
                "icon": "Boxes",
                "display_order": 30,
            },
            {
                "table_code": "stock_ledger",
                "table_name": "Stock Ledger",
                "module": "inventory",
                "submodule": "stock",
                "frontend_path": "/inventory/stock-ledger",
                "backend_endpoint": "/api/stock-ledger/",
                "search_keywords": ["ledger", "movement", "history", "stock ledger"],
                "importable": False,
                "exportable": True,
                "description": "Stock movement history and ledger",
                "icon": "BookOpen",
                "db_table_name": "StockLedger",
                "model_class": "tables.StockLedger",
                "display_order": 31,
            },
            {
                "table_code": "batches",
                "table_name": "Batches",
                "module": "inventory",
                "submodule": "stock",
                "frontend_path": "/inventory/batches",
                "backend_endpoint": "/api/batches/",
                "search_keywords": ["batch", "batches", "lot", "lot number"],
                "importable": False,
                "exportable": True,
                "description": "Batch and lot tracking",
                "icon": "Package",
                "db_table_name": "Batches",
                "model_class": "tables.Batches",
                "display_order": 32,
            },

            # Inventory module - Transactions
            {
                "table_code": "purchase",
                "table_name": "Purchases",
                "module": "inventory",
                "submodule": "transactions",
                "frontend_path": "/inventory/purchases",
                "backend_endpoint": "/api/purchases/",
                "search_keywords": ["purchase", "purchases", "buying", "procurement"],
                "importable": True,
                "exportable": True,
                "description": "Purchase orders and procurement",
                "icon": "ShoppingCart",
                "db_table_name": "Purchase",
                "model_class": "tables.Purchase",
                "display_order": 40,
            },
            {
                "table_code": "grn",
                "table_name": "GRN",
                "module": "inventory",
                "submodule": "transactions",
                "frontend_path": "/inventory/grn",
                "backend_endpoint": "/api/grn/",
                "search_keywords": ["grn", "goods received note", "goods receipt"],
                "importable": True,
                "exportable": True,
                "description": "Goods Received Notes",
                "icon": "ClipboardCheck",
                "db_table_name": "GoodRecivingNote",
                "model_class": "tables.GoodRecivingNote",
                "display_order": 41,
            },
            {
                "table_code": "stock_entries",
                "table_name": "Stock Entries",
                "module": "inventory",
                "submodule": "transactions",
                "frontend_path": "/inventory/stock-entries",
                "backend_endpoint": "/api/stock-entries/",
                "search_keywords": ["stock entry", "stock entries", "stock in", "goods receipt"],
                "importable": True,
                "exportable": True,
                "description": "Stock entry transactions",
                "icon": "ArrowDownLeft",
                "db_table_name": "StockEntry",
                "model_class": "tables.StockEntry",
                "display_order": 42,
            },
            {
                "table_code": "stock_outs",
                "table_name": "Stock Out Register",
                "module": "inventory",
                "submodule": "transactions",
                "frontend_path": "/inventory/stock-outs",
                "backend_endpoint": "/api/stock-outs/",
                "search_keywords": ["sales", "stock out", "stock-outs", "issue", "dispense", "sales register"],
                "importable": True,
                "exportable": True,
                "description": "Sales and stock out transactions",
                "icon": "ArrowUpRight",
                "db_table_name": "Sale",
                "model_class": "tables.Sale",
                "display_order": 43,
            },
            {
                "table_code": "stock_adjustments",
                "table_name": "Stock Adjustments",
                "module": "inventory",
                "submodule": "transactions",
                "frontend_path": "/inventory/stock-adjustments",
                "backend_endpoint": "/api/stock-adjustments/",
                "search_keywords": ["adjustments", "adjustment", "stock"],
                "importable": True,
                "exportable": True,
                "description": "Stock adjustment transactions",
                "icon": "Scale",
                "db_table_name": "StockAdjustment",
                "model_class": "tables.StockAdjustment",
                "display_order": 44,
            },

            # Inventory module - Returns
            {
                "table_code": "sales_returns",
                "table_name": "Customer Returns",
                "module": "inventory",
                "submodule": "returns",
                "frontend_path": "/inventory/sales-returns",
                "backend_endpoint": "/api/sales-returns/",
                "search_keywords": ["sales return", "returns", "customer returns"],
                "importable": False,
                "exportable": True,
                "description": "Customer sales returns",
                "icon": "RotateCcw",
                "db_table_name": "SalesReturn",
                "model_class": "tables.SalesReturn",
                "display_order": 50,
            },
            {
                "table_code": "supplier_returns",
                "table_name": "Supplier Returns",
                "module": "inventory",
                "submodule": "returns",
                "frontend_path": "/inventory/supplier-returns",
                "backend_endpoint": "/api/supplier-returns/",
                "search_keywords": ["supplier return", "returns", "vendor returns"],
                "importable": False,
                "exportable": True,
                "description": "Returns to suppliers",
                "icon": "Undo2",
                "db_table_name": "SupplierReturn",
                "model_class": "tables.SupplierReturn",
                "display_order": 51,
            },

            # Inventory module - Reports
            {
                "table_code": "near_expiry",
                "table_name": "Near Expiry Report",
                "module": "inventory",
                "submodule": "reports",
                "frontend_path": "/inventory/near-expiry",
                "backend_endpoint": "/api/reports/near-expiry/",
                "search_keywords": ["expiry", "expiring", "near expiry", "report"],
                "importable": False,
                "exportable": True,
                "description": "Near expiry items report",
                "icon": "AlertTriangle",
                "display_order": 60,
            },
            {
                "table_code": "inventory_status",
                "table_name": "Inventory Status Report",
                "module": "inventory",
                "submodule": "reports",
                "frontend_path": "/inventory/inventory-control-report",
                "backend_endpoint": "/api/reports/inventory-status/",
                "search_keywords": ["inventory status", "control report", "stock report", "report"],
                "importable": False,
                "exportable": True,
                "description": "Current inventory status report",
                "icon": "BarChart3",
                "display_order": 61,
            },
            {
                "table_code": "valuation",
                "table_name": "Valuation Report",
                "module": "inventory",
                "submodule": "reports",
                "frontend_path": "/inventory/valuation",
                "backend_endpoint": "/api/reports/valuation/",
                "search_keywords": ["valuation", "value", "report"],
                "importable": False,
                "exportable": True,
                "description": "Inventory valuation report",
                "icon": "DollarSign",
                "db_table_name": "InventoryValuation",
                "model_class": "tables.InventoryValuation",
                "display_order": 62,
            },
            {
                "table_code": "sales_summary",
                "table_name": "Sales Summary",
                "module": "inventory",
                "submodule": "reports",
                "frontend_path": "/inventory/sales-summary",
                "backend_endpoint": "/api/reports/sales-summary/",
                "search_keywords": ["sales summary", "sales", "report"],
                "importable": False,
                "exportable": True,
                "description": "Sales summary report",
                "icon": "TrendingUp",
                "display_order": 63,
            },

            # HR module
            {
                "table_code": "hr",
                "table_name": "HR",
                "module": "hr",
                "submodule": "hub",
                "frontend_path": "/hr",
                "backend_endpoint": "/api/hr/",
                "search_keywords": ["hr", "human resource", "human resources"],
                "importable": False,
                "exportable": False,
                "description": "Human Resources management hub",
                "icon": "Briefcase",
                "display_order": 100,
            },
            {
                "table_code": "hr_departments",
                "table_name": "Departments",
                "module": "hr",
                "submodule": "master_data",
                "frontend_path": "/hr/departments",
                "backend_endpoint": "/api/hr/departments/",
                "search_keywords": ["department", "departments"],
                "importable": True,
                "exportable": True,
                "description": "HR departments",
                "icon": "Building2",
                "display_order": 110,
            },
            {
                "table_code": "hr_employees",
                "table_name": "Employees",
                "module": "hr",
                "submodule": "master_data",
                "frontend_path": "/hr/employees",
                "backend_endpoint": "/api/hr/employees/",
                "search_keywords": ["employee", "employees", "staff"],
                "importable": True,
                "exportable": True,
                "description": "Employee master data",
                "icon": "UserCircle",
                "display_order": 111,
            },
            {
                "table_code": "hr_leave",
                "table_name": "Leave",
                "module": "hr",
                "submodule": "operations",
                "frontend_path": "/hr/leave",
                "backend_endpoint": "/api/hr/leave/",
                "search_keywords": ["leave", "time off"],
                "importable": False,
                "exportable": True,
                "description": "Employee leave management",
                "icon": "Calendar",
                "display_order": 120,
            },
            {
                "table_code": "hr_attendance",
                "table_name": "Attendance",
                "module": "hr",
                "submodule": "operations",
                "frontend_path": "/hr/attendance",
                "backend_endpoint": "/api/hr/attendance/",
                "search_keywords": ["attendance", "clock in"],
                "importable": False,
                "exportable": True,
                "description": "Employee attendance tracking",
                "icon": "Clock",
                "display_order": 121,
            },
            {
                "table_code": "hr_performance",
                "table_name": "Performance",
                "module": "hr",
                "submodule": "operations",
                "frontend_path": "/hr/performance",
                "backend_endpoint": "/api/hr/performance/",
                "search_keywords": ["performance", "reviews"],
                "importable": False,
                "exportable": True,
                "description": "Employee performance reviews",
                "icon": "Target",
                "display_order": 122,
            },
            {
                "table_code": "hr_payroll",
                "table_name": "Payroll",
                "module": "hr",
                "submodule": "operations",
                "frontend_path": "/hr/payroll",
                "backend_endpoint": "/api/hr/payroll/",
                "search_keywords": ["payroll", "salary", "wages"],
                "importable": False,
                "exportable": True,
                "description": "Payroll processing",
                "icon": "Banknote",
                "display_order": 123,
            },

            # Manufacturing module
            {
                "table_code": "manufacturing",
                "table_name": "Manufacturing",
                "module": "manufacturing",
                "submodule": "hub",
                "frontend_path": "/manufacturing",
                "backend_endpoint": "/api/manufacturing/",
                "search_keywords": ["production", "manufacturing", "factory"],
                "importable": False,
                "exportable": False,
                "description": "Manufacturing and production management",
                "icon": "Factory",
                "display_order": 200,
            },
        ]

        created_count = 0
        updated_count = 0

        for table_data in tables_data:
            table_code = table_data["table_code"]

            # Try to get existing record
            try:
                registry = TableRegistry.objects.get(table_code=table_code)
                # Update existing
                for key, value in table_data.items():
                    setattr(registry, key, value)
                registry.save()
                updated_count += 1
                self.stdout.write(f"Updated: {table_code}")
            except TableRegistry.DoesNotExist:
                # Create new
                TableRegistry.objects.create(**table_data)
                created_count += 1
                self.stdout.write(f"Created: {table_code}")

        self.stdout.write(
            self.style.SUCCESS(
                f"\nSeeding complete! Created: {created_count}, Updated: {updated_count}"
            )
        )
