# Generated by Django 6.0.3 on 2026-03-31 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0003_alter_employee_gender_choices'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='profile_photo_url',
        ),
        migrations.AddField(
            model_name='employee',
            name='profile_photo',
            field=models.FileField(blank=True, null=True, upload_to='employees/profile_photos/'),
        ),
    ]
