# Generated by Django 6.0.3 on 2026-03-31 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0004_department'),
        ('hr', '0004_remove_employee_profile_photo_url_and_more'),
    ]

    operations = [
    ]
