# Generated by Django 6.0.3 on 2026-04-11 05:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0011_designation_and_employee_user_link'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='attendancerecord',
            new_name='AttendanceR_employe_ed3849_idx',
            old_name='AttendanceR_employe_7e4d0d_idx',
        ),
        migrations.RenameIndex(
            model_name='attendancerecord',
            new_name='AttendanceR_status_6d849e_idx',
            old_name='AttendanceR_status__66180a_idx',
        ),
        migrations.RenameIndex(
            model_name='employee',
            new_name='Employee_departm_27d38d_idx',
            old_name='Employee_departm_5acc5f_idx',
        ),
        migrations.RenameIndex(
            model_name='employee',
            new_name='Employee_designa_f0537c_idx',
            old_name='Employee_designa_923495_idx',
        ),
        migrations.RenameIndex(
            model_name='leaverequest',
            new_name='LeaveReques_employe_0d6025_idx',
            old_name='LeaveReques_employe_77f6dc_idx',
        ),
        migrations.RenameIndex(
            model_name='leaverequest',
            new_name='LeaveReques_leave_t_2ef043_idx',
            old_name='LeaveReques_leave_t_b8c61d_idx',
        ),
        migrations.AddIndex(
            model_name='attendancerecord',
            index=models.Index(fields=['naming_series'], name='AttendanceR_naming__7bf345_idx'),
        ),
    ]
