# Generated by Django 6.0.3 on 2026-04-11 05:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0014_expiry_notifications'),
        ('tables', '0027_tableregistry_columns'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='expirynotification',
            new_name='expnotif_stat_prio_idx',
            old_name='inventory_en_status_priority_idx',
        ),
        migrations.RenameIndex(
            model_name='expirynotification',
            new_name='expnotif_expiry_idx',
            old_name='inventory_en_expiry_date_idx',
        ),
        migrations.RenameIndex(
            model_name='expirynotification',
            new_name='expnotif_med_stat_idx',
            old_name='inventory_en_medicine_status_idx',
        ),
        migrations.AlterField(
            model_name='expiryconfig',
            name='name',
            field=models.CharField(default='default', max_length=100, unique=True),
        ),
        migrations.AddIndex(
            model_name='reorderalert',
            index=models.Index(fields=['status', 'priority'], name='ReorderAler_status_c9f165_idx'),
        ),
        migrations.AddIndex(
            model_name='reorderalert',
            index=models.Index(fields=['medicine', 'status'], name='ReorderAler_medicin_278556_idx'),
        ),
    ]
