from django.urls import path

from .views import (
    batch_detail,
    dashboard_summary,
    global_search,
    inventory_list,
    medicine_categories_list,
    medicine_detail,
    medicine_detail_by_naming_series,
    medicine_logs,
    medicines_create,
    medicines_delete,
    medicines_list,
    medicines_update,
    stock_entries_create,
    stock_entries_list,
    stock_entry_cancel,
    stock_entry_detail,
    stock_entry_logs,
    stock_entry_submit,
    stock_entry_update,
    stock_out_batches,
    stock_out_cancel,
    stock_out_create,
    stock_out_detail,
    stock_out_detail_by_posting_number,
    stock_out_list,
    stock_out_logs,
    stock_out_submit,
    stock_out_update,
    supplier_cancel,
    supplier_create,
    supplier_detail,
    supplier_detail_by_naming_series,
    supplier_list,
    supplier_logs,
    supplier_update,
)

urlpatterns = [
    path("", inventory_list),
    path("batches/<int:batch_id>/", batch_detail),
    path("inventory-batches/<int:batch_id>/", batch_detail),
    path("dashboard/stats/", dashboard_summary),
    path("global-search/", global_search),
    path("medicines/", medicines_list),
    path("medicines/create/", medicines_create),
    path("medicines/update/<int:medicine_id>/", medicines_update),
    path("medicines/delete/<int:medicine_id>/", medicines_delete),
    path("medicine-categories/", medicine_categories_list),
    path("medicines/<int:medicine_id>/", medicine_detail),
    path("medicines/<int:medicine_id>/logs/", medicine_logs),
    path(
        "medicines/by-naming-series/<str:naming_series>/",
        medicine_detail_by_naming_series,
    ),
    path("medicines/supplier/", supplier_list),
    path("medicines/supplier/create/", supplier_create),
    path("medicines/supplier/<int:supplier_id>/", supplier_detail),
    path(
        "medicines/supplier/by-naming-series/<str:naming_series>/",
        supplier_detail_by_naming_series,
    ),
    path("medicines/supplier/<int:supplier_id>/update/", supplier_update),
    path("medicines/supplier/<int:supplier_id>/logs/", supplier_logs),
    path("medicines/supplier/<int:supplier_id>/cancel/", supplier_cancel),
    path("stock-entries/", stock_entries_list),
    path("stock-entries/<int:stock_entry_id>/", stock_entry_detail),
    path("stock-entries/<int:stock_entry_id>/logs/", stock_entry_logs),
    path("stock-entries/<int:stock_entry_id>/update/", stock_entry_update),
    path("stock-entries/<int:stock_entry_id>/submit/", stock_entry_submit),
    path("stock-entries/<int:stock_entry_id>/cancel/", stock_entry_cancel),
    path("stock-entries/create/", stock_entries_create),
    path("stock-outs/", stock_out_list),
    path("stock-outs/batches/", stock_out_batches),
    path("stock-outs/create/", stock_out_create),
    path("stock-outs/<int:sale_id>/", stock_out_detail),
    path(
        "stock-outs/by-posting-number/<str:posting_number>/",
        stock_out_detail_by_posting_number,
    ),
    path("stock-outs/<int:sale_id>/logs/", stock_out_logs),
    path("stock-outs/<int:sale_id>/update/", stock_out_update),
    path("stock-outs/<int:sale_id>/submit/", stock_out_submit),
    path("stock-outs/<int:sale_id>/cancel/", stock_out_cancel),
]
