from django.urls import path

from tables.views_table_registry import (
    TableRegistryListView,
    TableRegistrySearchView,
    TableRegistryDetailView,
    TableRegistryCreateView,
    TableRegistryUpdateView,
    TableRegistryDeleteView,
    TableRegistryModulesView,
    ImportableTablesView,
    TableSchemaView,
    TableImportPreviewView,
    TableImportExecuteView,
)

from .views import (
    audit_logs_list,
    batch_detail,
    category_create,
    category_delete,
    category_detail,
    category_detail_by_naming_series,
    category_logs,
    category_update,
    clear_application_cache,
    dashboard_summary,
    global_search,
    grn_detail,
    grn_list,
    inventory_hub_summary,
    inventory_list,
    medicine_categories_list,
    medicine_detail,
    medicine_detail_by_naming_series,
    medicine_logs,
    medicines_export,
    medicines_import,
    medicines_import_preview,
    medicines_create,
    medicines_delete,
    medicines_list,
    medicines_update,
    purchase_detail,
    purchases_list,
    print_formats_list,
    print_formats_create,
    print_formats_delete,
    print_formats_update,
    report_cogs_summary,
    report_inventory_valuation,
    report_medicine_cost_layers,
    report_medicine_profit_trend,
    report_near_expiry,
    report_profit_by_medicine,
    report_sales_summary,
    report_stock_valuation,
    sales_return_cancel,
    sales_return_create,
    sales_return_detail,
    sales_return_logs,
    sales_return_submit,
    sales_return_update,
    sales_returns_list,
    stock_adjustment_cancel,
    stock_adjustment_create,
    stock_adjustment_detail,
    stock_adjustment_logs,
    stock_adjustment_submit,
    stock_adjustment_update,
    stock_adjustments_list,
    stock_entries_create,
    stock_entries_list,
    stock_entry_cancel,
    stock_entry_delete,
    stock_entry_detail,
    stock_entry_detail_by_posting_number,
    stock_entry_logs,
    stock_entry_submit,
    stock_entry_update,
    stock_ledger_list,
    stock_out_batches,
    stock_out_cancel,
    stock_out_create,
    stock_out_delete,
    stock_out_detail,
    stock_out_detail_by_posting_number,
    stock_out_list,
    stock_out_logs,
    stock_out_submit,
    stock_out_update,
    supplier_cancel,
    supplier_create,
    supplier_delete,
    supplier_detail,
    supplier_detail_by_naming_series,
    supplier_list,
    supplier_logs,
    supplier_return_cancel,
    supplier_return_create,
    supplier_return_detail,
    supplier_return_logs,
    supplier_return_submit,
    supplier_return_update,
    supplier_returns_list,
    supplier_update,
)

urlpatterns = [
    # Table Registry endpoints
    path("tables/", TableRegistryListView.as_view(), name="table-registry-list"),
    path("tables/create/", TableRegistryCreateView.as_view(), name="table-registry-create"),
    path("tables/search/", TableRegistrySearchView.as_view(), name="table-registry-search"),
    path("tables/modules/", TableRegistryModulesView.as_view(), name="table-registry-modules"),
    path("tables/importable/", ImportableTablesView.as_view(), name="table-registry-importable"),
    path("tables/<str:table_code>/", TableRegistryDetailView.as_view(), name="table-registry-detail"),
    path("tables/<str:table_code>/update/", TableRegistryUpdateView.as_view(), name="table-registry-update"),
    path("tables/<str:table_code>/delete/", TableRegistryDeleteView.as_view(), name="table-registry-delete"),
    path("tables/<str:table_code>/schema/", TableSchemaView.as_view(), name="table-schema"),
    path("tables/<str:table_code>/import-preview/", TableImportPreviewView.as_view(), name="table-import-preview"),
    path("tables/<str:table_code>/import/", TableImportExecuteView.as_view(), name="table-import-execute"),

    path("", inventory_list),
    path("batches/<int:batch_id>/", batch_detail),
    path("inventory-batches/<int:batch_id>/", batch_detail),
    path("cache/clear/", clear_application_cache),
    path("hub/summary/", inventory_hub_summary),
    path("dashboard/stats/", dashboard_summary),
    path("global-search/", global_search),
    path("audit-logs/", audit_logs_list),
    path("print-formats/", print_formats_list),
    path("print-formats/create/", print_formats_create),
    path("print-formats/<int:print_format_id>/update/", print_formats_update),
    path("print-formats/<int:print_format_id>/delete/", print_formats_delete),
    path("stock-ledger/", stock_ledger_list),
    path("reports/near-expiry/", report_near_expiry),
    path("reports/valuation/", report_stock_valuation),
    path("reports/sales-summary/", report_sales_summary),
    path("reports/cogs-summary/", report_cogs_summary),
    path("reports/inventory-valuation/", report_inventory_valuation),
    path("reports/profit-by-medicine/", report_profit_by_medicine),
    path("reports/medicine/<int:medicine_id>/cost-layers/", report_medicine_cost_layers),
    path("reports/medicine/<int:medicine_id>/profit-trend/", report_medicine_profit_trend),
    path("purchases/", purchases_list),
    path("purchases/<int:purchase_id>/", purchase_detail),
    path("grn/", grn_list),
    path("grn/<int:grn_id>/", grn_detail),
    path("stock-adjustments/", stock_adjustments_list),
    path("stock-adjustments/create/", stock_adjustment_create),
    path("stock-adjustments/<int:adjustment_id>/", stock_adjustment_detail),
    path("stock-adjustments/<int:adjustment_id>/logs/", stock_adjustment_logs),
    path("stock-adjustments/<int:adjustment_id>/update/", stock_adjustment_update),
    path("stock-adjustments/<int:adjustment_id>/submit/", stock_adjustment_submit),
    path("stock-adjustments/<int:adjustment_id>/cancel/", stock_adjustment_cancel),
    path("sales-returns/", sales_returns_list),
    path("sales-returns/create/", sales_return_create),
    path("sales-returns/<int:return_id>/", sales_return_detail),
    path("sales-returns/<int:return_id>/logs/", sales_return_logs),
    path("sales-returns/<int:return_id>/update/", sales_return_update),
    path("sales-returns/<int:return_id>/submit/", sales_return_submit),
    path("sales-returns/<int:return_id>/cancel/", sales_return_cancel),
    path("supplier-returns/", supplier_returns_list),
    path("supplier-returns/create/", supplier_return_create),
    path("supplier-returns/<int:return_id>/", supplier_return_detail),
    path("supplier-returns/<int:return_id>/logs/", supplier_return_logs),
    path("supplier-returns/<int:return_id>/update/", supplier_return_update),
    path("supplier-returns/<int:return_id>/submit/", supplier_return_submit),
    path("supplier-returns/<int:return_id>/cancel/", supplier_return_cancel),
    path("medicines/", medicines_list),
    path("medicines/export/", medicines_export),
    path("medicines/import/preview/", medicines_import_preview),
    path("medicines/import/", medicines_import),
    path("medicines/create/", medicines_create),
    path("medicines/update/<int:medicine_id>/", medicines_update),
    path("medicines/delete/<int:medicine_id>/", medicines_delete),
    path("medicine-categories/", medicine_categories_list),
    path("medicine-categories/create/", category_create),
    path("medicine-categories/<int:category_id>/", category_detail),
    path(
        "medicine-categories/by-naming-series/<str:naming_series>/",
        category_detail_by_naming_series,
    ),
    path("medicine-categories/<int:category_id>/update/", category_update),
    path("medicine-categories/<int:category_id>/logs/", category_logs),
    path("medicine-categories/<int:category_id>/delete/", category_delete),
    path("medicines/<int:medicine_id>/", medicine_detail),
    path("medicines/<int:medicine_id>/logs/", medicine_logs),
    path(
        "medicines/by-naming-series/<str:naming_series>/",
        medicine_detail_by_naming_series,
    ),
    path("medicines/supplier/", supplier_list),
    path("medicines/supplier/create/", supplier_create),
    path("medicines/supplier/<int:supplier_id>/", supplier_detail),
    path(
        "medicines/supplier/by-naming-series/<str:naming_series>/",
        supplier_detail_by_naming_series,
    ),
    path("medicines/supplier/<int:supplier_id>/update/", supplier_update),
    path("medicines/supplier/<int:supplier_id>/logs/", supplier_logs),
    path("medicines/supplier/<int:supplier_id>/cancel/", supplier_cancel),
    path("medicines/supplier/<int:supplier_id>/delete/", supplier_delete),
    path("stock-entries/", stock_entries_list),
    path("stock-entries/<int:stock_entry_id>/", stock_entry_detail),
    path(
        "stock-entries/by-posting-number/<str:posting_number>/",
        stock_entry_detail_by_posting_number,
    ),
    path("stock-entries/<int:stock_entry_id>/logs/", stock_entry_logs),
    path("stock-entries/<int:stock_entry_id>/update/", stock_entry_update),
    path("stock-entries/<int:stock_entry_id>/submit/", stock_entry_submit),
    path("stock-entries/<int:stock_entry_id>/cancel/", stock_entry_cancel),
    path("stock-entries/<int:stock_entry_id>/delete/", stock_entry_delete),
    path("stock-entries/create/", stock_entries_create),
    path("stock-outs/", stock_out_list),
    path("stock-outs/batches/", stock_out_batches),
    path("stock-outs/create/", stock_out_create),
    path("stock-outs/<int:sale_id>/", stock_out_detail),
    path(
        "stock-outs/by-posting-number/<str:posting_number>/",
        stock_out_detail_by_posting_number,
    ),
    path("stock-outs/<int:sale_id>/logs/", stock_out_logs),
    path("stock-outs/<int:sale_id>/update/", stock_out_update),
    path("stock-outs/<int:sale_id>/submit/", stock_out_submit),
    path("stock-outs/<int:sale_id>/cancel/", stock_out_cancel),
    path("stock-outs/<int:sale_id>/delete/", stock_out_delete),
]
