from django.urls import path

from .views import (
    attendance_check_in,
    attendance_check_out,
    attendance_meta,
    attendance_record_create,
    attendance_record_detail_by_naming_series,
    attendance_record_list,
    attendance_record_update,
    department_create,
    department_delete,
    department_detail,
    department_list,
    department_update,
    designation_create,
    designation_delete,
    designation_detail,
    designation_list,
    designation_update,
    employee_create,
    employee_delete,
    employee_detail,
    employee_detail_by_naming_series,
    employee_filters,
    employee_list,
    employee_update,
    leave_meta,
    leave_request_approve,
    leave_request_cancel,
    leave_request_create,
    leave_request_list,
    leave_request_reject,
    leave_request_update,
    leave_type_create,
    leave_type_delete,
    leave_type_list,
    leave_type_update,
)

urlpatterns = [
    path("departments/", department_list),
    path("departments/create/", department_create),
    path("departments/<int:department_id>/", department_detail),
    path("departments/<int:department_id>/update/", department_update),
    path("departments/<int:department_id>/delete/", department_delete),
    path("designations/", designation_list),
    path("designations/create/", designation_create),
    path("designations/<int:designation_id>/", designation_detail),
    path("designations/<int:designation_id>/update/", designation_update),
    path("designations/<int:designation_id>/delete/", designation_delete),
    path("employees/", employee_list),
    path("employees/create/", employee_create),
    path("employees/filters/", employee_filters),
    path("employees/<int:employee_id>/", employee_detail),
    path("employees/<int:employee_id>/update/", employee_update),
    path("employees/<int:employee_id>/delete/", employee_delete),
    path(
        "employees/by-naming-series/<str:naming_series>/",
        employee_detail_by_naming_series,
    ),
    path("leave/meta/", leave_meta),
    path("leave/types/", leave_type_list),
    path("leave/types/create/", leave_type_create),
    path("leave/types/<int:leave_type_id>/update/", leave_type_update),
    path("leave/types/<int:leave_type_id>/delete/", leave_type_delete),
    path("leave/requests/", leave_request_list),
    path("leave/requests/create/", leave_request_create),
    path("leave/requests/<int:leave_request_id>/update/", leave_request_update),
    path("leave/requests/<int:leave_request_id>/approve/", leave_request_approve),
    path("leave/requests/<int:leave_request_id>/reject/", leave_request_reject),
    path("leave/requests/<int:leave_request_id>/cancel/", leave_request_cancel),
    path("attendance/meta/", attendance_meta),
    path("attendance/records/", attendance_record_list),
    path("attendance/records/create/", attendance_record_create),
    path(
        "attendance/records/by-naming-series/<str:naming_series>/",
        attendance_record_detail_by_naming_series,
    ),
    path(
        "attendance/records/by-naming-series/<str:naming_series>/update/",
        attendance_record_update,
    ),
    path("attendance/check-in/", attendance_check_in),
    path("attendance/check-out/", attendance_check_out),
]

