# Generated by Django 6.0.2 on 2026-02-20 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0002_inventoryhub_alter_inventory_medicine_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='inventory',
            options={'verbose_name_plural': 'Inventory'},
        ),
        migrations.AlterModelOptions(
            name='medicine',
            options={'verbose_name_plural': 'Medicines'},
        ),
        migrations.AlterModelOptions(
            name='purchase',
            options={'verbose_name_plural': 'Purchases'},
        ),
        migrations.AlterModelOptions(
            name='purchaseitem',
            options={'verbose_name_plural': 'Purchase Items'},
        ),
        migrations.AlterModelOptions(
            name='sale',
            options={'verbose_name_plural': 'Sales'},
        ),
        migrations.AlterModelOptions(
            name='saleitem',
            options={'verbose_name_plural': 'Sale Items'},
        ),
        migrations.AlterModelOptions(
            name='supplier',
            options={'verbose_name_plural': 'Suppliers'},
        ),
        migrations.AlterUniqueTogether(
            name='inventory',
            unique_together=set(),
        ),
        migrations.AlterModelTable(
            name='category',
            table='Category',
        ),
        migrations.AlterModelTable(
            name='inventory',
            table='Inventory',
        ),
        migrations.AlterModelTable(
            name='medicine',
            table='Medicine',
        ),
        migrations.AlterModelTable(
            name='purchase',
            table='Purchase',
        ),
        migrations.AlterModelTable(
            name='purchaseitem',
            table='PurchaseItem',
        ),
        migrations.AlterModelTable(
            name='sale',
            table='Sale',
        ),
        migrations.AlterModelTable(
            name='saleitem',
            table='SaleItem',
        ),
        migrations.AlterModelTable(
            name='supplier',
            table='Supplier',
        ),
    ]
