# Generated by Django 6.0.2 on 2026-03-03 10:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0003_alter_category_options_alter_inventory_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Batches',
            fields=[
                ('batch_id', models.AutoField(primary_key=True, serialize=False)),
                ('batch_number', models.CharField(max_length=50, unique=True)),
                ('expiry_date', models.DateField()),
                ('manufacturing_date', models.DateField()),
                ('quantity', models.IntegerField()),
                ('purchase_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tables.medicine')),
                ('supplier_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tables.supplier')),
            ],
            options={
                'verbose_name_plural': 'Batches',
                'db_table': 'Batches',
            },
        ),
        migrations.CreateModel(
            name='GoodRecivingNote',
            fields=[
                ('good_reciving_note_id', models.AutoField(primary_key=True, serialize=False)),
                ('invoice_number', models.CharField(max_length=50)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('purchase', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tables.purchase')),
                ('received_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('supplier_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tables.supplier')),
            ],
            options={
                'verbose_name_plural': 'Good Reciving Notes',
                'db_table': 'Good Reciving Note',
            },
        ),
        migrations.CreateModel(
            name='GoodRecivingNoteItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('expiry_date', models.DateField()),
                ('batch_number', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tables.batches')),
                ('good_reciving_note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tables.goodrecivingnote')),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tables.medicine')),
            ],
            options={
                'verbose_name_plural': 'Good Reciving Note Items',
                'db_table': 'GoodRecivingNoteItem',
            },
        ),
        migrations.CreateModel(
            name='StockLedger',
            fields=[
                ('transaction_id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.IntegerField()),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('reference_document', models.CharField(max_length=50)),
                ('notes', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('batch_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tables.batches')),
                ('medicine_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tables.medicine')),
            ],
            options={
                'verbose_name_plural': 'Stock Ledgers',
                'db_table': 'StockLedger',
            },
        ),
        migrations.CreateModel(
            name='UserLog',
            fields=[
                ('log_id', models.AutoField(primary_key=True, serialize=False)),
                ('action', models.CharField(max_length=100)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('details', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'User Logs',
                'db_table': 'UserLog',
            },
        ),
        migrations.AddField(
            model_name='purchase',
            name='grand_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='purchase',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='purchase',
            name='tax',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='generic_name',
            field=models.CharField(blank=True, db_index=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='name',
            field=models.CharField(db_index=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='purchaseitem',
            name='batch_number',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tables.batches'),
        ),
        migrations.AddIndex(
            model_name='inventory',
            index=models.Index(fields=['medicine', 'batch_number'], name='Inventory_medicin_dfd83d_idx'),
        ),
        migrations.AddIndex(
            model_name='purchase',
            index=models.Index(fields=['supplier', 'created_at', 'received_by'], name='Purchase_supplie_8fdec7_idx'),
        ),
        migrations.AddIndex(
            model_name='sale',
            index=models.Index(fields=['cashier', 'created_at'], name='Sale_cashier_291d45_idx'),
        ),
        migrations.AddIndex(
            model_name='saleitem',
            index=models.Index(fields=['sale', 'medicine'], name='SaleItem_sale_id_0248c3_idx'),
        ),
        migrations.AddIndex(
            model_name='supplier',
            index=models.Index(fields=['name'], name='Supplier_name_f00d3c_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaseitem',
            index=models.Index(fields=['purchase', 'medicine'], name='PurchaseIte_purchas_1aabba_idx'),
        ),
    ]
