# Generated by Django 6.0.2 on 2026-03-03 10:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0004_add_new_models'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='purchase',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'Purchases'},
        ),
        migrations.AddField(
            model_name='category',
            name='category_name',
            field=models.CharField(blank=True, db_index=True, max_length=150, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='category',
            name='parent_category_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tables.category'),
        ),
        migrations.AddField(
            model_name='purchase',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('ordered', 'Ordered'), ('partially_received', 'Partially Received'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='draft', max_length=20),
        ),
        migrations.AddField(
            model_name='purchase',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(db_index=True, max_length=150, unique=True),
        ),
    ]
