# Generated by Django 6.0.2 on 2026-03-03 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0005_add_additional_fields'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='parent_category_id',
            new_name='parent_category',
        ),
        migrations.RenameField(
            model_name='purchaseitem',
            old_name='batch_number',
            new_name='batch',
        ),
        migrations.RenameField(
            model_name='stockledger',
            old_name='batch_id',
            new_name='batch',
        ),
        migrations.RenameField(
            model_name='stockledger',
            old_name='medicine_id',
            new_name='medicine',
        ),
    ]
