# Generated by Django 6.0.2 on 2026-03-05 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0006_rename_parent_category_id_category_parent_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='status',
            field=models.CharField(choices=[('Draft', 'Draft'), ('Submitted', 'Submitted')], default='Draft', max_length=20),
        ),
        migrations.AddField(
            model_name='medicine',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
