# Generated by Django 6.0.2 on 2026-03-05 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0007_medicine_status_medicine_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='naming_series',
            field=models.CharField(blank=True, db_index=True, max_length=20, null=True, unique=True),
        ),
        migrations.CreateModel(
            name='MedicineNamingSeries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('series_name', models.CharField(default='medicine_series', max_length=50, unique=True)),
                ('current_number', models.PositiveIntegerField(default=0)),
                ('prefix', models.CharField(default='MED', max_length=10)),
                ('year', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Medicine Naming Series',
                'verbose_name_plural': 'Medicine Naming Series',
                'db_table': 'MedicineNamingSeries',
                'unique_together': {('prefix', 'year')},
            },
        ),
    ]
