# Generated by Django 6.0.3 on 2026-03-27 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0014_category_naming_series'),
        ('tables', '0014_saleitem_batch_tracking'),
    ]

    operations = [
    ]
