# Generated by Cursor on 2026-03-27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tables", "0015_merge_20260327_1432"),
    ]

    operations = [
        migrations.AddField(
            model_name="stockledger",
            name="transaction_type",
            field=models.CharField(
                choices=[
                    ("purchase", "Purchase"),
                    ("sale", "Sale"),
                    ("return", "Return"),
                    ("adjustment", "Adjustment"),
                    ("damage", "Damage"),
                ],
                default="purchase",
                max_length=20,
            ),
        ),
    ]

