# Generated by Cursor on 2026-03-27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tables", "0016_stockledger_transaction_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sale",
            name="invoice_number",
            field=models.CharField(blank=True, db_index=True, max_length=50),
        ),
    ]

