# Generated by Cursor on 2026-03-27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("tables", "0017_sale_invoice_number_optional"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="StockAdjustment",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("posting_number", models.CharField(blank=True, max_length=30, unique=True)),
                ("reason", models.CharField(choices=[("cycle_count", "Cycle Count"), ("write_off", "Write-off"), ("damage", "Damage"), ("expiry", "Expiry Disposal")], db_index=True, default="cycle_count", max_length=30)),
                ("status", models.CharField(choices=[("draft", "Draft"), ("posted", "Posted"), ("cancelled", "Cancelled")], db_index=True, default="draft", max_length=20)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_by", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="stock_adjustments", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "db_table": "StockAdjustment",
                "verbose_name_plural": "Stock Adjustments",
            },
        ),
        migrations.CreateModel(
            name="SalesReturn",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("posting_number", models.CharField(blank=True, max_length=30, unique=True)),
                ("reference_invoice", models.CharField(blank=True, db_index=True, max_length=50)),
                ("customer_name", models.CharField(blank=True, max_length=200)),
                ("status", models.CharField(choices=[("draft", "Draft"), ("posted", "Posted"), ("cancelled", "Cancelled")], db_index=True, default="draft", max_length=20)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_by", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="sales_returns", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "db_table": "SalesReturn",
                "verbose_name_plural": "Sales Returns",
            },
        ),
        migrations.CreateModel(
            name="SupplierReturn",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("posting_number", models.CharField(blank=True, max_length=30, unique=True)),
                ("reference_document", models.CharField(blank=True, db_index=True, max_length=50)),
                ("status", models.CharField(choices=[("draft", "Draft"), ("posted", "Posted"), ("cancelled", "Cancelled")], db_index=True, default="draft", max_length=20)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_by", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="supplier_returns", to=settings.AUTH_USER_MODEL)),
                ("supplier", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="tables.supplier")),
            ],
            options={
                "db_table": "SupplierReturn",
                "verbose_name_plural": "Supplier Returns",
            },
        ),
        migrations.CreateModel(
            name="StockAdjustmentItem",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("quantity_change", models.IntegerField()),
                ("unit_cost", models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("batch", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="tables.batches")),
                ("medicine", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="tables.medicine")),
                ("stock_adjustment", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="items", to="tables.stockadjustment")),
            ],
            options={
                "db_table": "StockAdjustmentItem",
                "verbose_name_plural": "Stock Adjustment Items",
            },
        ),
        migrations.CreateModel(
            name="SalesReturnItem",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("quantity", models.PositiveIntegerField()),
                ("unit_price", models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("batch", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="tables.batches")),
                ("medicine", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="tables.medicine")),
                ("sales_return", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="items", to="tables.salesreturn")),
            ],
            options={
                "db_table": "SalesReturnItem",
                "verbose_name_plural": "Sales Return Items",
            },
        ),
        migrations.CreateModel(
            name="SupplierReturnItem",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("quantity", models.PositiveIntegerField()),
                ("unit_price", models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("batch", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="tables.batches")),
                ("medicine", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="tables.medicine")),
                ("supplier_return", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="items", to="tables.supplierreturn")),
            ],
            options={
                "db_table": "SupplierReturnItem",
                "verbose_name_plural": "Supplier Return Items",
            },
        ),
        migrations.AddIndex(
            model_name="stockadjustmentitem",
            index=models.Index(fields=["stock_adjustment", "medicine"], name="StockAdjust_stock_a_92fb2c_idx"),
        ),
        migrations.AddIndex(
            model_name="salesreturnitem",
            index=models.Index(fields=["sales_return", "medicine"], name="SalesReturn_sales_r_6f5d01_idx"),
        ),
        migrations.AddIndex(
            model_name="supplierreturnitem",
            index=models.Index(fields=["supplier_return", "medicine"], name="SupplierRet_supplier_0ed0c6_idx"),
        ),
    ]

