# Generated by Django 6.0.3 on 2026-03-31 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0020_protect_document_item_links'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='sale',
            new_name='Sale_status_e6014d_idx',
            old_name='Sale_status_9b0f4b_idx',
        ),
        migrations.RenameIndex(
            model_name='sale',
            new_name='Sale_invoice_ea4a5b_idx',
            old_name='Sale_invoice_8d44ab_idx',
        ),
        migrations.RenameIndex(
            model_name='salesreturnitem',
            new_name='SalesReturn_sales_r_32e23a_idx',
            old_name='SalesReturn_sales_r_6f5d01_idx',
        ),
        migrations.RenameIndex(
            model_name='stockadjustmentitem',
            new_name='StockAdjust_stock_a_9486ba_idx',
            old_name='StockAdjust_stock_a_92fb2c_idx',
        ),
        migrations.RenameIndex(
            model_name='stockentry',
            new_name='StockEntry_supplie_517b4e_idx',
            old_name='StockEntry_supplie_770f4e_idx',
        ),
        migrations.RenameIndex(
            model_name='stockentry',
            new_name='StockEntry_status_c6f990_idx',
            old_name='StockEntry_status_32d4bb_idx',
        ),
        migrations.RenameIndex(
            model_name='stockentry',
            new_name='StockEntry_invoice_b87820_idx',
            old_name='StockEntry_invoice_21fef0_idx',
        ),
        migrations.RenameIndex(
            model_name='stockentryitem',
            new_name='StockEntryI_stock_e_50e899_idx',
            old_name='StockEntryI_stock_e_69f8ef_idx',
        ),
        migrations.RenameIndex(
            model_name='stockentryitem',
            new_name='StockEntryI_batch_i_0f4bd6_idx',
            old_name='StockEntryI_batch_i_a8ad4a_idx',
        ),
        migrations.RenameIndex(
            model_name='supplierreturnitem',
            new_name='SupplierRet_supplie_b5d0f6_idx',
            old_name='SupplierRet_supplier_0ed0c6_idx',
        ),
    ]
