# Generated by Django 6.0.3 on 2026-04-07 10:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0024_document_print_format_links'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_costing_method', models.CharField(choices=[('fifo', 'FIFO (First In, First Out)'), ('lifo', 'LIFO (Last In, First Out)'), ('fefo', 'FEFO (First Expired First Out)'), ('average', 'Average Cost')], default='fifo', max_length=20)),
                ('allow_costing_method_change', models.BooleanField(default=False, help_text='Changing costing method after transactions requires recalculation of all history')),
                ('low_stock_threshold_days', models.PositiveIntegerField(default=30, help_text='Warn when stock will expire within this many days')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'System Configuration',
                'db_table': 'SystemConfig',
            },
        ),
        migrations.AddField(
            model_name='medicine',
            name='costing_method',
            field=models.CharField(choices=[('fifo', 'FIFO (First In, First Out)'), ('lifo', 'LIFO (Last In, First Out)'), ('fefo', 'FEFO (First Expired First Out)'), ('average', 'Average Cost')], db_index=True, default='fifo', help_text='Costing method for calculating COGS on stock out', max_length=20),
        ),
        migrations.AddField(
            model_name='saleitem',
            name='calculated_cost',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Total cost of goods sold (COGS)', max_digits=12),
        ),
        migrations.AddField(
            model_name='saleitem',
            name='cost_layers_used',
            field=models.JSONField(default=list, help_text='Which cost layers were consumed: [{layer_id, quantity, unit_cost}, ...]'),
        ),
        migrations.AddField(
            model_name='saleitem',
            name='costing_method',
            field=models.CharField(choices=[('fifo', 'FIFO (First In, First Out)'), ('lifo', 'LIFO (Last In, First Out)'), ('fefo', 'FEFO (First Expired First Out)'), ('average', 'Average Cost')], default='fifo', help_text='Costing method used for this transaction', max_length=20),
        ),
        migrations.AddField(
            model_name='saleitem',
            name='unit_cost',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Average unit cost based on costing method', max_digits=10),
        ),
        migrations.AddField(
            model_name='salesreturnitem',
            name='cost_layers_restored',
            field=models.JSONField(default=list, help_text='New cost layers created from this return'),
        ),
        migrations.AddField(
            model_name='salesreturnitem',
            name='cost_to_restore',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Cost value being restored to inventory', max_digits=12),
        ),
        migrations.AddField(
            model_name='salesreturnitem',
            name='original_sale_item',
            field=models.ForeignKey(blank=True, help_text='Link to the original sale item (for cost tracking)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='returns', to='tables.saleitem'),
        ),
        migrations.AddField(
            model_name='stockadjustmentitem',
            name='adjustment_reason',
            field=models.CharField(blank=True, choices=[('damage', 'Damaged Goods'), ('expiry', 'Expired'), ('theft', 'Theft/Loss'), ('found', 'Stock Found'), ('other', 'Other')], max_length=100),
        ),
        migrations.AddField(
            model_name='stockadjustmentitem',
            name='cost_layers_affected',
            field=models.JSONField(default=list, help_text='Cost layers affected by this adjustment'),
        ),
        migrations.AddField(
            model_name='stockadjustmentitem',
            name='total_cost_adjustment',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Total value of cost adjustment', max_digits=12),
        ),
        migrations.AddField(
            model_name='supplierreturnitem',
            name='cost_layers_reversed',
            field=models.JSONField(default=list, help_text='Cost layers that were reversed/removed'),
        ),
        migrations.AddField(
            model_name='supplierreturnitem',
            name='linked_stock_entry_item',
            field=models.ForeignKey(blank=True, help_text='Link to the original stock entry (for cost tracking)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supplier_returns', to='tables.stockentryitem'),
        ),
        migrations.AddField(
            model_name='supplierreturnitem',
            name='total_cost_reversed',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Total cost value removed from inventory', max_digits=12),
        ),
        migrations.CreateModel(
            name='InventoryValuation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_quantity', models.PositiveIntegerField(default=0)),
                ('total_value', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('average_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('last_movement_at', models.DateTimeField(blank=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('medicine', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='valuation', to='tables.medicine')),
            ],
            options={
                'verbose_name_plural': 'Inventory Valuations',
                'db_table': 'InventoryValuation',
            },
        ),
        migrations.CreateModel(
            name='CostLayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('original_quantity', models.PositiveIntegerField()),
                ('remaining_quantity', models.PositiveIntegerField()),
                ('sequence_number', models.PositiveIntegerField(db_index=True)),
                ('expiry_date', models.DateField(blank=True, db_index=True, null=True)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('inventory', models.ForeignKey(blank=True, help_text='Link to the physical inventory/batch record', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cost_layers', to='tables.inventory')),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cost_layers', to='tables.medicine')),
                ('stock_entry_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cost_layers', to='tables.stockentryitem')),
            ],
            options={
                'verbose_name_plural': 'Cost Layers',
                'db_table': 'CostLayer',
                'ordering': ['medicine', 'sequence_number'],
                'indexes': [models.Index(fields=['medicine', 'remaining_quantity', 'sequence_number'], name='CostLayer_medicin_431af9_idx'), models.Index(fields=['medicine', 'remaining_quantity', 'expiry_date'], name='CostLayer_medicin_53aa31_idx')],
            },
        ),
    ]
