# Generated by Django 6.0.3 on 2026-04-08 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0025_systemconfig_medicine_costing_method_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TableRegistry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_code', models.CharField(db_index=True, help_text="Unique code for the table (e.g., 'medicine', 'category')", max_length=50, unique=True)),
                ('table_name', models.CharField(help_text="Display name of the table (e.g., 'Medicine Register')", max_length=100)),
                ('module', models.CharField(db_index=True, help_text="Module this table belongs to (e.g., 'inventory', 'hr', 'system')", max_length=50)),
                ('submodule', models.CharField(blank=True, help_text="Submodule classification (e.g., 'master_data', 'transactions')", max_length=50)),
                ('frontend_path', models.CharField(blank=True, help_text="Frontend route path (e.g., '/inventory/medicines')", max_length=200)),
                ('backend_endpoint', models.CharField(blank=True, help_text="Backend API endpoint (e.g., '/api/medicines/')", max_length=200)),
                ('search_keywords', models.JSONField(default=list, help_text='Array of search keywords for global search')),
                ('importable', models.BooleanField(default=False, help_text='Whether this table supports data import')),
                ('exportable', models.BooleanField(default=False, help_text='Whether this table supports data export')),
                ('import_template', models.CharField(blank=True, help_text='Path to import template file if applicable', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Description of what this table stores')),
                ('icon', models.CharField(blank=True, help_text="Icon name for UI (e.g., 'Package', 'Users', 'Settings')", max_length=50)),
                ('db_table_name', models.CharField(blank=True, help_text='Actual database table name', max_length=100)),
                ('model_class', models.CharField(blank=True, help_text="Django model class path (e.g., 'tables.Medicine')", max_length=100)),
                ('requires_auth', models.BooleanField(default=True, help_text='Whether authentication is required to access')),
                ('required_permissions', models.JSONField(default=list, help_text='Array of required permission codenames')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Whether this table is currently active/enabled')),
                ('is_system', models.BooleanField(default=False, help_text="Whether this is a system table that shouldn't be deleted")),
                ('display_order', models.PositiveIntegerField(default=0, help_text='Display order for listing')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Table Registries',
                'db_table': 'TableRegistry',
                'ordering': ['module', 'display_order', 'table_name'],
            },
        ),
    ]
