# Generated by Django 6.0.3 on 2026-04-08 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0026_tableregistry'),
    ]

    operations = [
        migrations.AddField(
            model_name='tableregistry',
            name='columns',
            field=models.JSONField(default=list, help_text='Column definitions for import/export. Each column has: name, label, type, required, description, example, include_in_import, include_in_export, is_identifier'),
        ),
    ]
